# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 91696d7a86b162d69d42637c8cf1473f674d054f5905ebad4437416daca3ac48c3f16003a5aa4faa876cabaf7a5d8d5b5e804863ade318038817ed9b2e6f019f

test:
  secret_key_base: 05ea3bbb926a8ef73a01db84b13c51b335de706f41bb24541952d95742c46916805aac807d653d8f046da6c4fb6fbd6da620d551da139476e1e56ccd2703bf7c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
